general {
    hide_cursor = false
    ignore_empty_input = true
    immediate_render = true
}

background {
    monitor =
    color = rgb(2E3440)
}

label {
    monitor =
    text = $TIME
    color = rgba(d3c6aaff)
    font_size = 64
    position = 0, 80
    halign = center
    valign = center
	font_family = FiraCode Nerd Font
}

input-field {
    monitor =
    size = 260, 52
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.18
    dots_center = true
    outer_color = rgb(88C0D0)
    inner_color = rgb(3B4252)
    font_color = rgba(d3c6aaff)
    font_family = FiraCode Nerd Font
    fade_on_empty = false
    placeholder_text = <span foreground="##d3c6aa">Password...</span>
    hide_input = false
    check_color = rgba(a7c080ff)
    fail_color = rgba(e67e80ff)
    fail_text = <i>$FAIL</i>
    capslock_color = rgba(dbbc7fff)
    position = 0, -40
    halign = center
    valign = center
}
