general {
    lock_cmd = pidof hyprlock || hyprlock --config ~/.config/hypr/hyprlock.conf
    after_sleep_cmd = hyprctl dispatch dpms on
    on_unlock_cmd = hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# Dim 10 seconds before lock
listener {
    timeout = 470
    on-timeout = brightnessctl -s set 20%
    on-resume = brightnessctl -r
}

# Lock at 8 minutes
listener {
    timeout = 480
    on-timeout = loginctl lock-session
}

# Turn display off 15 seconds after lock
listener {
    timeout = 495
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
